# Generated by Django 4.2 on 2023-07-28 23:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Whisper', '0002_rename_profile_proffile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proffile',
            new_name='profile',
        ),
    ]
